name: Node.js CI

on: [pull_request]

jobs:
  environment:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Setup node 14
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"
      - name: Install dependencies
        run: npm ci

  test:
    needs: setup-dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: npm run test
